services:
  db:
    ports:
      - 5432:5432
    container_name: postgres_todo_con
    image: postgres
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - /Users/alexkcheah/Documents/Project/todo_container_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      dockerfile: Dockerfile
    container_name: todo_app_con
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/todo
      db-username: admin
      db-password: admin
    depends_on:
      - db
    restart: always


